import { IServiceProvider } from './types';

export default {
  name: 'Grok',
  apiBase: 'https://api.x.ai/v1',
  currency: 'USD',
  options: {
    apiBaseCustomizable: true,
    apiKeyCustomizable: true,
  },
  chat: {
    apiSchema: ['base', 'key', 'model'],
    presencePenalty: { min: -2, max: 2, default: 0 },
    topP: { min: 0, max: 1, default: 1 },
    temperature: { min: 0, max: 2, default: 0.9 },
    options: {
      modelCustomizable: true,
    },
    models: {
      'grok-beta': {
        name: 'grok-beta',
        label: 'Grok Beta',
        contextWindow: 131072,
        defaultMaxTokens:4000,
        maxTokens: 4096,
        inputPrice: 5,
        outputPrice: 15,
        isDefault: true,
        vision: {
          enabled: true,
          allowBase64: true,
          allowUrl: true,
        },
        description: `✨ xAI's experimental language model with state-of-the-art reasoning capabilities, can search the internet for up-to-date information.\n\n📊 For experts: Successor to Grok 2 with enhanced context length of 131K tokens and improved reasoning capabilities.`,
        toolEnabled: true,
        onlineEnabled: true,
        group: 'Grok',
      },
      'grok-2-vision': {
        name: 'grok-2-vision',
        contextWindow: 32768,
        defaultMaxTokens:4000,
        maxTokens: 4096,
        inputPrice: 0.002,
        outputPrice: 0.01,
        isDefault: false,
        vision: {
          enabled: true,
          allowBase64: true,
          allowUrl: true,
        },
        description: `specialized model for advanced image generation and understanding`,
        toolEnabled: true,
        group: 'Grok',
      },
      'grok-2': {
        name: 'grok-2',
        contextWindow: 128000,
        defaultMaxTokens:128000,
        maxTokens: 128000,
        inputPrice: 0.002,
        outputPrice: 0.01,
        isDefault: false,
        description: `Comparable performance to Grok 2 but with improved efficiency, speed and capabilities.`,
        toolEnabled: true,
        group: 'Grok',
      },
    },
  },
} as IServiceProvider;
